name: 'Install .NET'
description: 'Install .NET SDK with proper environment variables for caching'

inputs:
  dotnet-version:
    description: 'The .NET SDK version to install'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set DOTNET_INSTALL_DIR (Linux/macOS)
      if: runner.os != 'Windows'
      shell: bash
      run: echo "DOTNET_INSTALL_DIR=$GITHUB_WORKSPACE/.dotnet" >> $GITHUB_ENV

    - name: Set DOTNET_INSTALL_DIR (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: echo "DOTNET_INSTALL_DIR=$env:GITHUB_WORKSPACE\.dotnet" >> $env:GITHUB_ENV

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
