<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<EnableMSTestRunner>true</EnableMSTestRunner>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MSTest" Version="$(MSTestVersion)" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Uno.HotTesting.Engine\Uno.HotTesting.Engine.csproj" />
	</ItemGroup>

</Project>
